/*
 * generated by Xtext 2.19.0
 */
package com.simonbaars.cdd.parser.antlr;

import com.google.inject.Inject;
import com.simonbaars.cdd.parser.antlr.internal.InternalCloneDetectionDSLParser;
import com.simonbaars.cdd.services.CloneDetectionDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CloneDetectionDSLParser extends AbstractAntlrParser {

	@Inject
	private CloneDetectionDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCloneDetectionDSLParser createParser(XtextTokenStream stream) {
		return new InternalCloneDetectionDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "CloneDetection";
	}

	public CloneDetectionDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CloneDetectionDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
