/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.cdd.cloneDetectionDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Boolean Expression Bracket</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.simonbaars.cdd.cloneDetectionDSL.BooleanExpressionBracket#getSub <em>Sub</em>}</li>
 * </ul>
 *
 * @see com.simonbaars.cdd.cloneDetectionDSL.CloneDetectionDSLPackage#getBooleanExpressionBracket()
 * @model
 * @generated
 */
public interface BooleanExpressionBracket extends BooleanExpression
{
  /**
   * Returns the value of the '<em><b>Sub</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub</em>' containment reference.
   * @see #setSub(BooleanExpression)
   * @see com.simonbaars.cdd.cloneDetectionDSL.CloneDetectionDSLPackage#getBooleanExpressionBracket_Sub()
   * @model containment="true"
   * @generated
   */
  BooleanExpression getSub();

  /**
   * Sets the value of the '{@link com.simonbaars.cdd.cloneDetectionDSL.BooleanExpressionBracket#getSub <em>Sub</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sub</em>' containment reference.
   * @see #getSub()
   * @generated
   */
  void setSub(BooleanExpression value);

} // BooleanExpressionBracket
