/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.cdd.cloneDetectionDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.simonbaars.cdd.cloneDetectionDSL.CloneDetectionDSLFactory
 * @model kind="package"
 * @generated
 */
public interface CloneDetectionDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cloneDetectionDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.simonbaars.com/cdd/CloneDetectionDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cloneDetectionDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CloneDetectionDSLPackage eINSTANCE = com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionImpl <em>Clone Detection</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionImpl
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getCloneDetection()
   * @generated
   */
  int CLONE_DETECTION = 0;

  /**
   * The feature id for the '<em><b>Project</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLONE_DETECTION__PROJECT = 0;

  /**
   * The feature id for the '<em><b>Root</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLONE_DETECTION__ROOT = 1;

  /**
   * The feature id for the '<em><b>Match</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLONE_DETECTION__MATCH = 2;

  /**
   * The feature id for the '<em><b>Exclude</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLONE_DETECTION__EXCLUDE = 3;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLONE_DETECTION__SIZE = 4;

  /**
   * The feature id for the '<em><b>Paths</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLONE_DETECTION__PATHS = 5;

  /**
   * The feature id for the '<em><b>Not Compare</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLONE_DETECTION__NOT_COMPARE = 6;

  /**
   * The feature id for the '<em><b>Compare</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLONE_DETECTION__COMPARE = 7;

  /**
   * The number of structural features of the '<em>Clone Detection</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLONE_DETECTION_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.ProjectImpl <em>Project</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.ProjectImpl
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getProject()
   * @generated
   */
  int PROJECT = 1;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT__PATH = 0;

  /**
   * The number of structural features of the '<em>Project</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROJECT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.LibraryPathImpl <em>Library Path</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.LibraryPathImpl
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getLibraryPath()
   * @generated
   */
  int LIBRARY_PATH = 2;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIBRARY_PATH__PATH = 0;

  /**
   * The number of structural features of the '<em>Library Path</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIBRARY_PATH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.SearchRootImpl <em>Search Root</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.SearchRootImpl
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getSearchRoot()
   * @generated
   */
  int SEARCH_ROOT = 3;

  /**
   * The feature id for the '<em><b>Nodes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEARCH_ROOT__NODES = 0;

  /**
   * The number of structural features of the '<em>Search Root</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEARCH_ROOT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.MatchImpl <em>Match</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.MatchImpl
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getMatch()
   * @generated
   */
  int MATCH = 4;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATCH__TARGET = 0;

  /**
   * The number of structural features of the '<em>Match</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MATCH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.ExcludeImpl <em>Exclude</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.ExcludeImpl
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getExclude()
   * @generated
   */
  int EXCLUDE = 5;

  /**
   * The number of structural features of the '<em>Exclude</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXCLUDE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.NodeImpl <em>Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.NodeImpl
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getNode()
   * @generated
   */
  int NODE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NAME = 0;

  /**
   * The feature id for the '<em><b>Under</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__UNDER = 1;

  /**
   * The feature id for the '<em><b>Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NODE = 2;

  /**
   * The number of structural features of the '<em>Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.NodesImpl <em>Nodes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.NodesImpl
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getNodes()
   * @generated
   */
  int NODES = 7;

  /**
   * The feature id for the '<em><b>Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODES__NODE = EXCLUDE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Nodes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODES__NODES = EXCLUDE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Nodes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODES_FEATURE_COUNT = EXCLUDE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.SizeImpl <em>Size</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.SizeImpl
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getSize()
   * @generated
   */
  int SIZE = 8;

  /**
   * The number of structural features of the '<em>Size</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.MinSizeImpl <em>Min Size</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.MinSizeImpl
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getMinSize()
   * @generated
   */
  int MIN_SIZE = 9;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIN_SIZE__EXPR = SIZE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Brackets</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIN_SIZE__BRACKETS = SIZE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIN_SIZE__OPERATOR = SIZE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIN_SIZE__SIZE = SIZE_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Min Size</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIN_SIZE_FEATURE_COUNT = SIZE_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.MetricExprImpl <em>Metric Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.MetricExprImpl
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getMetricExpr()
   * @generated
   */
  int METRIC_EXPR = 10;

  /**
   * The feature id for the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC_EXPR__AMOUNT = 0;

  /**
   * The feature id for the '<em><b>Metric</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC_EXPR__METRIC = 1;

  /**
   * The number of structural features of the '<em>Metric Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METRIC_EXPR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.DoNotCompareImpl <em>Do Not Compare</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.DoNotCompareImpl
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getDoNotCompare()
   * @generated
   */
  int DO_NOT_COMPARE = 11;

  /**
   * The number of structural features of the '<em>Do Not Compare</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DO_NOT_COMPARE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.CompareImpl <em>Compare</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CompareImpl
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getCompare()
   * @generated
   */
  int COMPARE = 12;

  /**
   * The feature id for the '<em><b>Nodes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARE__NODES = 0;

  /**
   * The feature id for the '<em><b>Comparison Method</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARE__COMPARISON_METHOD = 1;

  /**
   * The feature id for the '<em><b>Deepest Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARE__DEEPEST_NODE = 2;

  /**
   * The feature id for the '<em><b>Perc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARE__PERC = 3;

  /**
   * The number of structural features of the '<em>Compare</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.MatchTarget <em>Match Target</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.MatchTarget
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getMatchTarget()
   * @generated
   */
  int MATCH_TARGET = 13;

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.SizeMetric <em>Size Metric</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.SizeMetric
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getSizeMetric()
   * @generated
   */
  int SIZE_METRIC = 14;

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.BoolOperator <em>Bool Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.BoolOperator
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getBoolOperator()
   * @generated
   */
  int BOOL_OPERATOR = 15;

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.Method <em>Method</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.Method
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getMethod()
   * @generated
   */
  int METHOD = 16;

  /**
   * The meta object id for the '{@link com.simonbaars.cdd.cloneDetectionDSL.Under <em>Under</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.simonbaars.cdd.cloneDetectionDSL.Under
   * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getUnder()
   * @generated
   */
  int UNDER = 17;


  /**
   * Returns the meta object for class '{@link com.simonbaars.cdd.cloneDetectionDSL.CloneDetection <em>Clone Detection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Clone Detection</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.CloneDetection
   * @generated
   */
  EClass getCloneDetection();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.cdd.cloneDetectionDSL.CloneDetection#getProject <em>Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Project</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.CloneDetection#getProject()
   * @see #getCloneDetection()
   * @generated
   */
  EReference getCloneDetection_Project();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.cdd.cloneDetectionDSL.CloneDetection#isRoot <em>Root</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Root</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.CloneDetection#isRoot()
   * @see #getCloneDetection()
   * @generated
   */
  EAttribute getCloneDetection_Root();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.cdd.cloneDetectionDSL.CloneDetection#isMatch <em>Match</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Match</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.CloneDetection#isMatch()
   * @see #getCloneDetection()
   * @generated
   */
  EAttribute getCloneDetection_Match();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.cdd.cloneDetectionDSL.CloneDetection#isExclude <em>Exclude</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Exclude</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.CloneDetection#isExclude()
   * @see #getCloneDetection()
   * @generated
   */
  EAttribute getCloneDetection_Exclude();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.cdd.cloneDetectionDSL.CloneDetection#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Size</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.CloneDetection#getSize()
   * @see #getCloneDetection()
   * @generated
   */
  EReference getCloneDetection_Size();

  /**
   * Returns the meta object for the containment reference list '{@link com.simonbaars.cdd.cloneDetectionDSL.CloneDetection#getPaths <em>Paths</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Paths</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.CloneDetection#getPaths()
   * @see #getCloneDetection()
   * @generated
   */
  EReference getCloneDetection_Paths();

  /**
   * Returns the meta object for the containment reference list '{@link com.simonbaars.cdd.cloneDetectionDSL.CloneDetection#getNotCompare <em>Not Compare</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Not Compare</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.CloneDetection#getNotCompare()
   * @see #getCloneDetection()
   * @generated
   */
  EReference getCloneDetection_NotCompare();

  /**
   * Returns the meta object for the containment reference list '{@link com.simonbaars.cdd.cloneDetectionDSL.CloneDetection#getCompare <em>Compare</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Compare</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.CloneDetection#getCompare()
   * @see #getCloneDetection()
   * @generated
   */
  EReference getCloneDetection_Compare();

  /**
   * Returns the meta object for class '{@link com.simonbaars.cdd.cloneDetectionDSL.Project <em>Project</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Project</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Project
   * @generated
   */
  EClass getProject();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.cdd.cloneDetectionDSL.Project#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Project#getPath()
   * @see #getProject()
   * @generated
   */
  EAttribute getProject_Path();

  /**
   * Returns the meta object for class '{@link com.simonbaars.cdd.cloneDetectionDSL.LibraryPath <em>Library Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Library Path</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.LibraryPath
   * @generated
   */
  EClass getLibraryPath();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.cdd.cloneDetectionDSL.LibraryPath#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.LibraryPath#getPath()
   * @see #getLibraryPath()
   * @generated
   */
  EAttribute getLibraryPath_Path();

  /**
   * Returns the meta object for class '{@link com.simonbaars.cdd.cloneDetectionDSL.SearchRoot <em>Search Root</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Search Root</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.SearchRoot
   * @generated
   */
  EClass getSearchRoot();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.cdd.cloneDetectionDSL.SearchRoot#getNodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nodes</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.SearchRoot#getNodes()
   * @see #getSearchRoot()
   * @generated
   */
  EReference getSearchRoot_Nodes();

  /**
   * Returns the meta object for class '{@link com.simonbaars.cdd.cloneDetectionDSL.Match <em>Match</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Match</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Match
   * @generated
   */
  EClass getMatch();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.cdd.cloneDetectionDSL.Match#getTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Match#getTarget()
   * @see #getMatch()
   * @generated
   */
  EAttribute getMatch_Target();

  /**
   * Returns the meta object for class '{@link com.simonbaars.cdd.cloneDetectionDSL.Exclude <em>Exclude</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exclude</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Exclude
   * @generated
   */
  EClass getExclude();

  /**
   * Returns the meta object for class '{@link com.simonbaars.cdd.cloneDetectionDSL.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Node
   * @generated
   */
  EClass getNode();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.cdd.cloneDetectionDSL.Node#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Node#getName()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_Name();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.cdd.cloneDetectionDSL.Node#getUnder <em>Under</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Under</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Node#getUnder()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_Under();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.cdd.cloneDetectionDSL.Node#getNode <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Node</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Node#getNode()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Node();

  /**
   * Returns the meta object for class '{@link com.simonbaars.cdd.cloneDetectionDSL.Nodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nodes</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Nodes
   * @generated
   */
  EClass getNodes();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.cdd.cloneDetectionDSL.Nodes#getNode <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Node</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Nodes#getNode()
   * @see #getNodes()
   * @generated
   */
  EReference getNodes_Node();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.cdd.cloneDetectionDSL.Nodes#getNodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nodes</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Nodes#getNodes()
   * @see #getNodes()
   * @generated
   */
  EReference getNodes_Nodes();

  /**
   * Returns the meta object for class '{@link com.simonbaars.cdd.cloneDetectionDSL.Size <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Size</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Size
   * @generated
   */
  EClass getSize();

  /**
   * Returns the meta object for class '{@link com.simonbaars.cdd.cloneDetectionDSL.MinSize <em>Min Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Min Size</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.MinSize
   * @generated
   */
  EClass getMinSize();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.cdd.cloneDetectionDSL.MinSize#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.MinSize#getExpr()
   * @see #getMinSize()
   * @generated
   */
  EReference getMinSize_Expr();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.cdd.cloneDetectionDSL.MinSize#getBrackets <em>Brackets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Brackets</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.MinSize#getBrackets()
   * @see #getMinSize()
   * @generated
   */
  EReference getMinSize_Brackets();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.cdd.cloneDetectionDSL.MinSize#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.MinSize#getOperator()
   * @see #getMinSize()
   * @generated
   */
  EAttribute getMinSize_Operator();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.cdd.cloneDetectionDSL.MinSize#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Size</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.MinSize#getSize()
   * @see #getMinSize()
   * @generated
   */
  EReference getMinSize_Size();

  /**
   * Returns the meta object for class '{@link com.simonbaars.cdd.cloneDetectionDSL.MetricExpr <em>Metric Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metric Expr</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.MetricExpr
   * @generated
   */
  EClass getMetricExpr();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.cdd.cloneDetectionDSL.MetricExpr#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amount</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.MetricExpr#getAmount()
   * @see #getMetricExpr()
   * @generated
   */
  EAttribute getMetricExpr_Amount();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.cdd.cloneDetectionDSL.MetricExpr#getMetric <em>Metric</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Metric</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.MetricExpr#getMetric()
   * @see #getMetricExpr()
   * @generated
   */
  EAttribute getMetricExpr_Metric();

  /**
   * Returns the meta object for class '{@link com.simonbaars.cdd.cloneDetectionDSL.DoNotCompare <em>Do Not Compare</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Do Not Compare</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.DoNotCompare
   * @generated
   */
  EClass getDoNotCompare();

  /**
   * Returns the meta object for class '{@link com.simonbaars.cdd.cloneDetectionDSL.Compare <em>Compare</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Compare</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Compare
   * @generated
   */
  EClass getCompare();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.cdd.cloneDetectionDSL.Compare#getNodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nodes</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Compare#getNodes()
   * @see #getCompare()
   * @generated
   */
  EReference getCompare_Nodes();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.cdd.cloneDetectionDSL.Compare#getComparisonMethod <em>Comparison Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparison Method</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Compare#getComparisonMethod()
   * @see #getCompare()
   * @generated
   */
  EAttribute getCompare_ComparisonMethod();

  /**
   * Returns the meta object for the containment reference '{@link com.simonbaars.cdd.cloneDetectionDSL.Compare#getDeepestNode <em>Deepest Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Deepest Node</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Compare#getDeepestNode()
   * @see #getCompare()
   * @generated
   */
  EReference getCompare_DeepestNode();

  /**
   * Returns the meta object for the attribute '{@link com.simonbaars.cdd.cloneDetectionDSL.Compare#getPerc <em>Perc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Perc</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Compare#getPerc()
   * @see #getCompare()
   * @generated
   */
  EAttribute getCompare_Perc();

  /**
   * Returns the meta object for enum '{@link com.simonbaars.cdd.cloneDetectionDSL.MatchTarget <em>Match Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Match Target</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.MatchTarget
   * @generated
   */
  EEnum getMatchTarget();

  /**
   * Returns the meta object for enum '{@link com.simonbaars.cdd.cloneDetectionDSL.SizeMetric <em>Size Metric</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Size Metric</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.SizeMetric
   * @generated
   */
  EEnum getSizeMetric();

  /**
   * Returns the meta object for enum '{@link com.simonbaars.cdd.cloneDetectionDSL.BoolOperator <em>Bool Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Bool Operator</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.BoolOperator
   * @generated
   */
  EEnum getBoolOperator();

  /**
   * Returns the meta object for enum '{@link com.simonbaars.cdd.cloneDetectionDSL.Method <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Method</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Method
   * @generated
   */
  EEnum getMethod();

  /**
   * Returns the meta object for enum '{@link com.simonbaars.cdd.cloneDetectionDSL.Under <em>Under</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Under</em>'.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Under
   * @generated
   */
  EEnum getUnder();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CloneDetectionDSLFactory getCloneDetectionDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionImpl <em>Clone Detection</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionImpl
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getCloneDetection()
     * @generated
     */
    EClass CLONE_DETECTION = eINSTANCE.getCloneDetection();

    /**
     * The meta object literal for the '<em><b>Project</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLONE_DETECTION__PROJECT = eINSTANCE.getCloneDetection_Project();

    /**
     * The meta object literal for the '<em><b>Root</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLONE_DETECTION__ROOT = eINSTANCE.getCloneDetection_Root();

    /**
     * The meta object literal for the '<em><b>Match</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLONE_DETECTION__MATCH = eINSTANCE.getCloneDetection_Match();

    /**
     * The meta object literal for the '<em><b>Exclude</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLONE_DETECTION__EXCLUDE = eINSTANCE.getCloneDetection_Exclude();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLONE_DETECTION__SIZE = eINSTANCE.getCloneDetection_Size();

    /**
     * The meta object literal for the '<em><b>Paths</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLONE_DETECTION__PATHS = eINSTANCE.getCloneDetection_Paths();

    /**
     * The meta object literal for the '<em><b>Not Compare</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLONE_DETECTION__NOT_COMPARE = eINSTANCE.getCloneDetection_NotCompare();

    /**
     * The meta object literal for the '<em><b>Compare</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLONE_DETECTION__COMPARE = eINSTANCE.getCloneDetection_Compare();

    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.ProjectImpl <em>Project</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.ProjectImpl
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getProject()
     * @generated
     */
    EClass PROJECT = eINSTANCE.getProject();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROJECT__PATH = eINSTANCE.getProject_Path();

    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.LibraryPathImpl <em>Library Path</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.LibraryPathImpl
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getLibraryPath()
     * @generated
     */
    EClass LIBRARY_PATH = eINSTANCE.getLibraryPath();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIBRARY_PATH__PATH = eINSTANCE.getLibraryPath_Path();

    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.SearchRootImpl <em>Search Root</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.SearchRootImpl
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getSearchRoot()
     * @generated
     */
    EClass SEARCH_ROOT = eINSTANCE.getSearchRoot();

    /**
     * The meta object literal for the '<em><b>Nodes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEARCH_ROOT__NODES = eINSTANCE.getSearchRoot_Nodes();

    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.MatchImpl <em>Match</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.MatchImpl
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getMatch()
     * @generated
     */
    EClass MATCH = eINSTANCE.getMatch();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MATCH__TARGET = eINSTANCE.getMatch_Target();

    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.ExcludeImpl <em>Exclude</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.ExcludeImpl
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getExclude()
     * @generated
     */
    EClass EXCLUDE = eINSTANCE.getExclude();

    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.NodeImpl <em>Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.NodeImpl
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getNode()
     * @generated
     */
    EClass NODE = eINSTANCE.getNode();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__NAME = eINSTANCE.getNode_Name();

    /**
     * The meta object literal for the '<em><b>Under</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__UNDER = eINSTANCE.getNode_Under();

    /**
     * The meta object literal for the '<em><b>Node</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__NODE = eINSTANCE.getNode_Node();

    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.NodesImpl <em>Nodes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.NodesImpl
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getNodes()
     * @generated
     */
    EClass NODES = eINSTANCE.getNodes();

    /**
     * The meta object literal for the '<em><b>Node</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODES__NODE = eINSTANCE.getNodes_Node();

    /**
     * The meta object literal for the '<em><b>Nodes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODES__NODES = eINSTANCE.getNodes_Nodes();

    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.SizeImpl <em>Size</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.SizeImpl
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getSize()
     * @generated
     */
    EClass SIZE = eINSTANCE.getSize();

    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.MinSizeImpl <em>Min Size</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.MinSizeImpl
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getMinSize()
     * @generated
     */
    EClass MIN_SIZE = eINSTANCE.getMinSize();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MIN_SIZE__EXPR = eINSTANCE.getMinSize_Expr();

    /**
     * The meta object literal for the '<em><b>Brackets</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MIN_SIZE__BRACKETS = eINSTANCE.getMinSize_Brackets();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MIN_SIZE__OPERATOR = eINSTANCE.getMinSize_Operator();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MIN_SIZE__SIZE = eINSTANCE.getMinSize_Size();

    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.MetricExprImpl <em>Metric Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.MetricExprImpl
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getMetricExpr()
     * @generated
     */
    EClass METRIC_EXPR = eINSTANCE.getMetricExpr();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METRIC_EXPR__AMOUNT = eINSTANCE.getMetricExpr_Amount();

    /**
     * The meta object literal for the '<em><b>Metric</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METRIC_EXPR__METRIC = eINSTANCE.getMetricExpr_Metric();

    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.DoNotCompareImpl <em>Do Not Compare</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.DoNotCompareImpl
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getDoNotCompare()
     * @generated
     */
    EClass DO_NOT_COMPARE = eINSTANCE.getDoNotCompare();

    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.impl.CompareImpl <em>Compare</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CompareImpl
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getCompare()
     * @generated
     */
    EClass COMPARE = eINSTANCE.getCompare();

    /**
     * The meta object literal for the '<em><b>Nodes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARE__NODES = eINSTANCE.getCompare_Nodes();

    /**
     * The meta object literal for the '<em><b>Comparison Method</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARE__COMPARISON_METHOD = eINSTANCE.getCompare_ComparisonMethod();

    /**
     * The meta object literal for the '<em><b>Deepest Node</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARE__DEEPEST_NODE = eINSTANCE.getCompare_DeepestNode();

    /**
     * The meta object literal for the '<em><b>Perc</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARE__PERC = eINSTANCE.getCompare_Perc();

    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.MatchTarget <em>Match Target</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.MatchTarget
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getMatchTarget()
     * @generated
     */
    EEnum MATCH_TARGET = eINSTANCE.getMatchTarget();

    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.SizeMetric <em>Size Metric</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.SizeMetric
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getSizeMetric()
     * @generated
     */
    EEnum SIZE_METRIC = eINSTANCE.getSizeMetric();

    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.BoolOperator <em>Bool Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.BoolOperator
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getBoolOperator()
     * @generated
     */
    EEnum BOOL_OPERATOR = eINSTANCE.getBoolOperator();

    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.Method <em>Method</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.Method
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getMethod()
     * @generated
     */
    EEnum METHOD = eINSTANCE.getMethod();

    /**
     * The meta object literal for the '{@link com.simonbaars.cdd.cloneDetectionDSL.Under <em>Under</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.simonbaars.cdd.cloneDetectionDSL.Under
     * @see com.simonbaars.cdd.cloneDetectionDSL.impl.CloneDetectionDSLPackageImpl#getUnder()
     * @generated
     */
    EEnum UNDER = eINSTANCE.getUnder();

  }

} //CloneDetectionDSLPackage
