/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.cdd.cloneDetectionDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.simonbaars.cdd.cloneDetectionDSL.IntExpression#getMetric <em>Metric</em>}</li>
 * </ul>
 *
 * @see com.simonbaars.cdd.cloneDetectionDSL.CloneDetectionDSLPackage#getIntExpression()
 * @model
 * @generated
 */
public interface IntExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Metric</b></em>' attribute.
   * The literals are from the enumeration {@link com.simonbaars.cdd.cloneDetectionDSL.Metric}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metric</em>' attribute.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Metric
   * @see #setMetric(Metric)
   * @see com.simonbaars.cdd.cloneDetectionDSL.CloneDetectionDSLPackage#getIntExpression_Metric()
   * @model
   * @generated
   */
  Metric getMetric();

  /**
   * Sets the value of the '{@link com.simonbaars.cdd.cloneDetectionDSL.IntExpression#getMetric <em>Metric</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Metric</em>' attribute.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Metric
   * @see #getMetric()
   * @generated
   */
  void setMetric(Metric value);

} // IntExpression
