/*
 * generated by Xtext 2.19.0
 */
package com.simonbaars.cdd.ui.tests;

import com.google.inject.Injector;
import com.simonbaars.cdd.ui.internal.CddActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CloneDetectionDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CddActivator.getInstance().getInjector("com.simonbaars.cdd.CloneDetectionDSL");
	}

}
