/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.cdd.ui;

import com.simonbaars.cdd.ui.AbstractCloneDetectionDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CloneDetectionDSLUiModule extends AbstractCloneDetectionDSLUiModule {
  public CloneDetectionDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
