/*
 * generated by Xtext 2.19.0
 */
package com.simonbaars.cdd.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CloneDetectionDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/simonbaars/cdd/parser/antlr/internal/InternalCloneDetectionDSL.tokens");
	}
}
