/*
 * generated by Xtext 2.19.0
 */
package com.simonbaars.cdd


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CloneDetectionDSLStandaloneSetup extends CloneDetectionDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new CloneDetectionDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
