/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.cdd.ui.contentassist;

import com.simonbaars.cdd.ui.contentassist.AbstractCloneDetectionDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CloneDetectionDSLProposalProvider extends AbstractCloneDetectionDSLProposalProvider {
}
