/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.cdd.cloneDetectionDSL.util;

import com.simonbaars.cdd.cloneDetectionDSL.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see com.simonbaars.cdd.cloneDetectionDSL.CloneDetectionDSLPackage
 * @generated
 */
public class CloneDetectionDSLAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static CloneDetectionDSLPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CloneDetectionDSLAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = CloneDetectionDSLPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CloneDetectionDSLSwitch<Adapter> modelSwitch =
    new CloneDetectionDSLSwitch<Adapter>()
    {
      @Override
      public Adapter caseCloneDetection(CloneDetection object)
      {
        return createCloneDetectionAdapter();
      }
      @Override
      public Adapter caseProject(Project object)
      {
        return createProjectAdapter();
      }
      @Override
      public Adapter caseSearchRoot(SearchRoot object)
      {
        return createSearchRootAdapter();
      }
      @Override
      public Adapter caseMatch(Match object)
      {
        return createMatchAdapter();
      }
      @Override
      public Adapter caseExclude(Exclude object)
      {
        return createExcludeAdapter();
      }
      @Override
      public Adapter caseNode(Node object)
      {
        return createNodeAdapter();
      }
      @Override
      public Adapter caseNodes(Nodes object)
      {
        return createNodesAdapter();
      }
      @Override
      public Adapter caseMinSize(MinSize object)
      {
        return createMinSizeAdapter();
      }
      @Override
      public Adapter caseMetricExpr(MetricExpr object)
      {
        return createMetricExprAdapter();
      }
      @Override
      public Adapter caseDoNotCompare(DoNotCompare object)
      {
        return createDoNotCompareAdapter();
      }
      @Override
      public Adapter caseCompare(Compare object)
      {
        return createCompareAdapter();
      }
      @Override
      public Adapter caseBooleanExpression(BooleanExpression object)
      {
        return createBooleanExpressionAdapter();
      }
      @Override
      public Adapter caseNotExpression(NotExpression object)
      {
        return createNotExpressionAdapter();
      }
      @Override
      public Adapter caseBooleanExpressionBracket(BooleanExpressionBracket object)
      {
        return createBooleanExpressionBracketAdapter();
      }
      @Override
      public Adapter caseBooleanExpressionConstant(BooleanExpressionConstant object)
      {
        return createBooleanExpressionConstantAdapter();
      }
      @Override
      public Adapter caseIntExpression(IntExpression object)
      {
        return createIntExpressionAdapter();
      }
      @Override
      public Adapter caseExpressionMinus(ExpressionMinus object)
      {
        return createExpressionMinusAdapter();
      }
      @Override
      public Adapter caseExpressionPlus(ExpressionPlus object)
      {
        return createExpressionPlusAdapter();
      }
      @Override
      public Adapter caseExpressionBracket(ExpressionBracket object)
      {
        return createExpressionBracketAdapter();
      }
      @Override
      public Adapter caseExpressionConstantInt(ExpressionConstantInt object)
      {
        return createExpressionConstantIntAdapter();
      }
      @Override
      public Adapter caseExpressionBinOp(ExpressionBinOp object)
      {
        return createExpressionBinOpAdapter();
      }
      @Override
      public Adapter caseExpressionCompOp(ExpressionCompOp object)
      {
        return createExpressionCompOpAdapter();
      }
      @Override
      public Adapter caseExpressionAddition(ExpressionAddition object)
      {
        return createExpressionAdditionAdapter();
      }
      @Override
      public Adapter caseExpressionSubtraction(ExpressionSubtraction object)
      {
        return createExpressionSubtractionAdapter();
      }
      @Override
      public Adapter caseExpressionMultiply(ExpressionMultiply object)
      {
        return createExpressionMultiplyAdapter();
      }
      @Override
      public Adapter caseExpressionDivision(ExpressionDivision object)
      {
        return createExpressionDivisionAdapter();
      }
      @Override
      public Adapter caseExpressionMaximum(ExpressionMaximum object)
      {
        return createExpressionMaximumAdapter();
      }
      @Override
      public Adapter caseExpressionMinimum(ExpressionMinimum object)
      {
        return createExpressionMinimumAdapter();
      }
      @Override
      public Adapter caseExpressionModulo(ExpressionModulo object)
      {
        return createExpressionModuloAdapter();
      }
      @Override
      public Adapter caseExpressionPower(ExpressionPower object)
      {
        return createExpressionPowerAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.CloneDetection <em>Clone Detection</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.CloneDetection
   * @generated
   */
  public Adapter createCloneDetectionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.Project <em>Project</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Project
   * @generated
   */
  public Adapter createProjectAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.SearchRoot <em>Search Root</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.SearchRoot
   * @generated
   */
  public Adapter createSearchRootAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.Match <em>Match</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Match
   * @generated
   */
  public Adapter createMatchAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.Exclude <em>Exclude</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Exclude
   * @generated
   */
  public Adapter createExcludeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Node
   * @generated
   */
  public Adapter createNodeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.Nodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Nodes
   * @generated
   */
  public Adapter createNodesAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.MinSize <em>Min Size</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.MinSize
   * @generated
   */
  public Adapter createMinSizeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.MetricExpr <em>Metric Expr</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.MetricExpr
   * @generated
   */
  public Adapter createMetricExprAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.DoNotCompare <em>Do Not Compare</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.DoNotCompare
   * @generated
   */
  public Adapter createDoNotCompareAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.Compare <em>Compare</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.Compare
   * @generated
   */
  public Adapter createCompareAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.BooleanExpression <em>Boolean Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.BooleanExpression
   * @generated
   */
  public Adapter createBooleanExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.NotExpression <em>Not Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.NotExpression
   * @generated
   */
  public Adapter createNotExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.BooleanExpressionBracket <em>Boolean Expression Bracket</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.BooleanExpressionBracket
   * @generated
   */
  public Adapter createBooleanExpressionBracketAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.BooleanExpressionConstant <em>Boolean Expression Constant</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.BooleanExpressionConstant
   * @generated
   */
  public Adapter createBooleanExpressionConstantAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.IntExpression <em>Int Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.IntExpression
   * @generated
   */
  public Adapter createIntExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.ExpressionMinus <em>Expression Minus</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.ExpressionMinus
   * @generated
   */
  public Adapter createExpressionMinusAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.ExpressionPlus <em>Expression Plus</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.ExpressionPlus
   * @generated
   */
  public Adapter createExpressionPlusAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.ExpressionBracket <em>Expression Bracket</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.ExpressionBracket
   * @generated
   */
  public Adapter createExpressionBracketAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.ExpressionConstantInt <em>Expression Constant Int</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.ExpressionConstantInt
   * @generated
   */
  public Adapter createExpressionConstantIntAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.ExpressionBinOp <em>Expression Bin Op</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.ExpressionBinOp
   * @generated
   */
  public Adapter createExpressionBinOpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.ExpressionCompOp <em>Expression Comp Op</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.ExpressionCompOp
   * @generated
   */
  public Adapter createExpressionCompOpAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.ExpressionAddition <em>Expression Addition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.ExpressionAddition
   * @generated
   */
  public Adapter createExpressionAdditionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.ExpressionSubtraction <em>Expression Subtraction</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.ExpressionSubtraction
   * @generated
   */
  public Adapter createExpressionSubtractionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.ExpressionMultiply <em>Expression Multiply</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.ExpressionMultiply
   * @generated
   */
  public Adapter createExpressionMultiplyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.ExpressionDivision <em>Expression Division</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.ExpressionDivision
   * @generated
   */
  public Adapter createExpressionDivisionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.ExpressionMaximum <em>Expression Maximum</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.ExpressionMaximum
   * @generated
   */
  public Adapter createExpressionMaximumAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.ExpressionMinimum <em>Expression Minimum</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.ExpressionMinimum
   * @generated
   */
  public Adapter createExpressionMinimumAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.ExpressionModulo <em>Expression Modulo</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.ExpressionModulo
   * @generated
   */
  public Adapter createExpressionModuloAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link com.simonbaars.cdd.cloneDetectionDSL.ExpressionPower <em>Expression Power</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see com.simonbaars.cdd.cloneDetectionDSL.ExpressionPower
   * @generated
   */
  public Adapter createExpressionPowerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //CloneDetectionDSLAdapterFactory
