/**
 * generated by Xtext 2.19.0
 */
package com.simonbaars.cdd.cloneDetectionDSL.util;

import com.simonbaars.cdd.cloneDetectionDSL.*;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see com.simonbaars.cdd.cloneDetectionDSL.CloneDetectionDSLPackage
 * @generated
 */
public class CloneDetectionDSLSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static CloneDetectionDSLPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CloneDetectionDSLSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = CloneDetectionDSLPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case CloneDetectionDSLPackage.CLONE_DETECTION:
      {
        CloneDetection cloneDetection = (CloneDetection)theEObject;
        T result = caseCloneDetection(cloneDetection);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.PROJECT:
      {
        Project project = (Project)theEObject;
        T result = caseProject(project);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.SEARCH_ROOT:
      {
        SearchRoot searchRoot = (SearchRoot)theEObject;
        T result = caseSearchRoot(searchRoot);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.MATCH:
      {
        Match match = (Match)theEObject;
        T result = caseMatch(match);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.EXCLUDE:
      {
        Exclude exclude = (Exclude)theEObject;
        T result = caseExclude(exclude);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.NODE:
      {
        Node node = (Node)theEObject;
        T result = caseNode(node);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.NODES:
      {
        Nodes nodes = (Nodes)theEObject;
        T result = caseNodes(nodes);
        if (result == null) result = caseExclude(nodes);
        if (result == null) result = caseDoNotCompare(nodes);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.MIN_SIZE:
      {
        MinSize minSize = (MinSize)theEObject;
        T result = caseMinSize(minSize);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.METRIC_EXPR:
      {
        MetricExpr metricExpr = (MetricExpr)theEObject;
        T result = caseMetricExpr(metricExpr);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.DO_NOT_COMPARE:
      {
        DoNotCompare doNotCompare = (DoNotCompare)theEObject;
        T result = caseDoNotCompare(doNotCompare);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.COMPARE:
      {
        Compare compare = (Compare)theEObject;
        T result = caseCompare(compare);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.BOOLEAN_EXPRESSION:
      {
        BooleanExpression booleanExpression = (BooleanExpression)theEObject;
        T result = caseBooleanExpression(booleanExpression);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.NOT_EXPRESSION:
      {
        NotExpression notExpression = (NotExpression)theEObject;
        T result = caseNotExpression(notExpression);
        if (result == null) result = caseBooleanExpression(notExpression);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.BOOLEAN_EXPRESSION_BRACKET:
      {
        BooleanExpressionBracket booleanExpressionBracket = (BooleanExpressionBracket)theEObject;
        T result = caseBooleanExpressionBracket(booleanExpressionBracket);
        if (result == null) result = caseBooleanExpression(booleanExpressionBracket);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.BOOLEAN_EXPRESSION_CONSTANT:
      {
        BooleanExpressionConstant booleanExpressionConstant = (BooleanExpressionConstant)theEObject;
        T result = caseBooleanExpressionConstant(booleanExpressionConstant);
        if (result == null) result = caseBooleanExpression(booleanExpressionConstant);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.INT_EXPRESSION:
      {
        IntExpression intExpression = (IntExpression)theEObject;
        T result = caseIntExpression(intExpression);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.EXPRESSION_MINUS:
      {
        ExpressionMinus expressionMinus = (ExpressionMinus)theEObject;
        T result = caseExpressionMinus(expressionMinus);
        if (result == null) result = caseIntExpression(expressionMinus);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.EXPRESSION_PLUS:
      {
        ExpressionPlus expressionPlus = (ExpressionPlus)theEObject;
        T result = caseExpressionPlus(expressionPlus);
        if (result == null) result = caseIntExpression(expressionPlus);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.EXPRESSION_BRACKET:
      {
        ExpressionBracket expressionBracket = (ExpressionBracket)theEObject;
        T result = caseExpressionBracket(expressionBracket);
        if (result == null) result = caseIntExpression(expressionBracket);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.EXPRESSION_CONSTANT_INT:
      {
        ExpressionConstantInt expressionConstantInt = (ExpressionConstantInt)theEObject;
        T result = caseExpressionConstantInt(expressionConstantInt);
        if (result == null) result = caseIntExpression(expressionConstantInt);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.EXPRESSION_BIN_OP:
      {
        ExpressionBinOp expressionBinOp = (ExpressionBinOp)theEObject;
        T result = caseExpressionBinOp(expressionBinOp);
        if (result == null) result = caseBooleanExpression(expressionBinOp);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.EXPRESSION_COMP_OP:
      {
        ExpressionCompOp expressionCompOp = (ExpressionCompOp)theEObject;
        T result = caseExpressionCompOp(expressionCompOp);
        if (result == null) result = caseBooleanExpression(expressionCompOp);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.EXPRESSION_ADDITION:
      {
        ExpressionAddition expressionAddition = (ExpressionAddition)theEObject;
        T result = caseExpressionAddition(expressionAddition);
        if (result == null) result = caseIntExpression(expressionAddition);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.EXPRESSION_SUBTRACTION:
      {
        ExpressionSubtraction expressionSubtraction = (ExpressionSubtraction)theEObject;
        T result = caseExpressionSubtraction(expressionSubtraction);
        if (result == null) result = caseIntExpression(expressionSubtraction);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.EXPRESSION_MULTIPLY:
      {
        ExpressionMultiply expressionMultiply = (ExpressionMultiply)theEObject;
        T result = caseExpressionMultiply(expressionMultiply);
        if (result == null) result = caseIntExpression(expressionMultiply);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.EXPRESSION_DIVISION:
      {
        ExpressionDivision expressionDivision = (ExpressionDivision)theEObject;
        T result = caseExpressionDivision(expressionDivision);
        if (result == null) result = caseIntExpression(expressionDivision);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.EXPRESSION_MAXIMUM:
      {
        ExpressionMaximum expressionMaximum = (ExpressionMaximum)theEObject;
        T result = caseExpressionMaximum(expressionMaximum);
        if (result == null) result = caseIntExpression(expressionMaximum);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.EXPRESSION_MINIMUM:
      {
        ExpressionMinimum expressionMinimum = (ExpressionMinimum)theEObject;
        T result = caseExpressionMinimum(expressionMinimum);
        if (result == null) result = caseIntExpression(expressionMinimum);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.EXPRESSION_MODULO:
      {
        ExpressionModulo expressionModulo = (ExpressionModulo)theEObject;
        T result = caseExpressionModulo(expressionModulo);
        if (result == null) result = caseIntExpression(expressionModulo);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case CloneDetectionDSLPackage.EXPRESSION_POWER:
      {
        ExpressionPower expressionPower = (ExpressionPower)theEObject;
        T result = caseExpressionPower(expressionPower);
        if (result == null) result = caseIntExpression(expressionPower);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Clone Detection</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Clone Detection</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCloneDetection(CloneDetection object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Project</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Project</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseProject(Project object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Search Root</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Search Root</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseSearchRoot(SearchRoot object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Match</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Match</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMatch(Match object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Exclude</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Exclude</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExclude(Exclude object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Node</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Node</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseNode(Node object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Nodes</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Nodes</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseNodes(Nodes object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Min Size</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Min Size</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMinSize(MinSize object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Metric Expr</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Metric Expr</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMetricExpr(MetricExpr object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Do Not Compare</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Do Not Compare</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDoNotCompare(DoNotCompare object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Compare</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Compare</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCompare(Compare object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Boolean Expression</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Boolean Expression</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBooleanExpression(BooleanExpression object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Not Expression</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Not Expression</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseNotExpression(NotExpression object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Boolean Expression Bracket</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Boolean Expression Bracket</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBooleanExpressionBracket(BooleanExpressionBracket object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Boolean Expression Constant</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Boolean Expression Constant</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBooleanExpressionConstant(BooleanExpressionConstant object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Int Expression</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Int Expression</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseIntExpression(IntExpression object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Minus</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Minus</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionMinus(ExpressionMinus object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Plus</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Plus</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionPlus(ExpressionPlus object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Bracket</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Bracket</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionBracket(ExpressionBracket object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Constant Int</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Constant Int</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionConstantInt(ExpressionConstantInt object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Bin Op</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Bin Op</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionBinOp(ExpressionBinOp object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Comp Op</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Comp Op</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionCompOp(ExpressionCompOp object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Addition</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Addition</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionAddition(ExpressionAddition object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Subtraction</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Subtraction</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionSubtraction(ExpressionSubtraction object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Multiply</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Multiply</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionMultiply(ExpressionMultiply object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Division</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Division</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionDivision(ExpressionDivision object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Maximum</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Maximum</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionMaximum(ExpressionMaximum object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Minimum</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Minimum</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionMinimum(ExpressionMinimum object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Modulo</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Modulo</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionModulo(ExpressionModulo object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Expression Power</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Expression Power</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseExpressionPower(ExpressionPower object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //CloneDetectionDSLSwitch
